### ISSUE TITLE
Receive warnings when building vitahelloworld in cygwin

### ISSUE THREAD

**Issue by D-Pyro** [psp2dev/psp2sdk#60]
In file included from C:\devkitPro\devkitARM\psp2/include/stdio.h:37:0,
                 from main.c:5:
C:\devkitPro\devkitARM\psp2/include/malloc.h:51:40: warning: 'struct _reent' declared inside parameter list
 extern _PTR _malloc_r _PARAMS ((struct _reent *, size_t));
                                        ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:51:40: warning: its scope is only this definition or declaration, which is probably not what you want
C:\devkitPro\devkitARM\psp2/include/malloc.h:59:39: warning: 'struct _reent' declared inside parameter list
 extern _VOID _free_r _PARAMS ((struct _reent *, _PTR));
                                       ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:67:41: warning: 'struct _reent' declared inside parameter list
 extern _PTR _realloc_r _PARAMS ((struct _reent *, _PTR, size_t));
                                         ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:75:40: warning: 'struct _reent' declared inside parameter list
 extern _PTR _calloc_r _PARAMS ((struct _reent *, size_t, size_t));
                                        ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:83:42: warning: 'struct _reent' declared inside parameter list
 extern _PTR _memalign_r _PARAMS ((struct _reent *, size_t, size_t));
                                          ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:91:53: warning: 'struct _reent' declared inside parameter list
 extern struct mallinfo _mallinfo_r _PARAMS ((struct _reent *));
                                                     ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:99:46: warning: 'struct _reent' declared inside parameter list
 extern void _malloc_stats_r _PARAMS ((struct _reent *));
                                              ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:107:40: warning: 'struct _reent' declared inside parameter list
 extern int _mallopt_r _PARAMS ((struct _reent *, int, int));
                                        ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:115:54: warning: 'struct _reent' declared inside parameter list
 extern size_t _malloc_usable_size_r _PARAMS ((struct _reent *, _PTR));
                                                      ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:126:40: warning: 'struct _reent' declared inside parameter list
 extern _PTR _valloc_r _PARAMS ((struct _reent *, size_t));
                                        ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:134:41: warning: 'struct _reent' declared inside parameter list
 extern _PTR _pvalloc_r _PARAMS ((struct _reent *, size_t));
                                         ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:142:44: warning: 'struct _reent' declared inside parameter list
 extern int _malloc_trim_r _PARAMS ((struct _reent *, size_t));
                                            ^
C:\devkitPro\devkitARM\psp2/include/malloc.h:152:41: warning: 'struct _reent' declared inside parameter list
 extern _VOID _mstats_r _PARAMS ((struct _reent *, char *));

**Comment by 173210** [comment]
Fixed with commit 97a69be98fc1dd09f6b341de6d54f7413dc987fa in [psp2dev/libs](https://github.com/psp2dev/libs)
